# Generated by Django 4.1.2 on 2022-11-17 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=3000)),
            ],
            options={
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_street', models.CharField(max_length=30)),
                ('restaurant_zip', models.CharField(max_length=5)),
                ('restaurant_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud_restaurants.city')),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'restaurant_type',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_abbr', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('food_tried', models.ManyToManyField(blank=True, to='crud_restaurants.menuitem')),
                ('restaurants_visited', models.ManyToManyField(blank=True, to='crud_restaurants.restaurant')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RestaurantStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_style', models.CharField(max_length=30)),
                ('restaurant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_restaurants.restauranttype')),
            ],
            options={
                'db_table': 'restaurant_style',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud_restaurants.state'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_restaurants.restaurantstyle'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ManyToManyField(to='crud_restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud_restaurants.state'),
        ),
    ]
