# Generated by Django 4.1.2 on 2022-11-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_state',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_type_style',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_zip',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_restaurants.city'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_restaurants.state'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_restaurants.restaurantstyle'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_zip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_restaurants.zipcode'),
        ),
    ]
